backend:
  name: github
  repo: libertyjensenart/libertyjensenart.github.io
  branch: main
  base_url: https://api.sveltia.org

media_folder: "images"
public_folder: "/images"

collections:
  - name: "portfolio"
    label: "Portfolio Projects"
    folder: "_portfolio"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "select", options: ["digital-art", "web-design", "game-development"] }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Project Content", name: "body", widget: "markdown" }